### ISSUE TITLE
pickadate is using deprecated Jquery functions

### ISSUE THREAD

**Issue by krodneyk65RT** [amsul/pickadate.js#1252]
If you use the JQuery migrate tool as I do (see below) it reports the following:
jquery-migrate-3.4.1.js:136 JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray

isArray is still supported in JQ3.7.1 - but in future releases it will likely be removed.  I imagine pickadate is using other deprecated JQ functions - but this is the only one I ran across

<jsp:include page="/secure/inc/footer.jsp">
    <jsp:param name="scripts" value="/js/third-party/jquery-3.7.1.js"/>
    <jsp:param name="scripts" value="/js/third-party/jquery-migrate-3.4.1.js"/>
    <jsp:param name="scripts" value="/js/third-party/pickadate.js-3.6.2/lib/picker.js"/>
    <jsp:param name="scripts" value="/js/third-party/pickadate.js-3.6.2/lib/picker.date.js"/>
    <jsp:param name="scripts" value="/js/third-party/pickadate.js-3.6.2/lib/picker.time.js"/>

**Comment by robme** [comment]
Yes it doesn't work with jQuery 4.0 because of the error:

> .isArray is not a function

**Comment by robme** [comment]
So I see v5 has removed jQuery as a dependency, although it's in alpha and 6 years old. If that doesn't work, I'll see about replacing the `$.isArray()` calls with JavaScript `Array.isArray()` in v3.6.4.
